"""
rl_analysis.py — Generate training and policy analysis plots for the DQN agent.

Produces two plots:
    1. logs/plot_reward_curve.png
       Scatter of episode reward per episode + rolling average line.
       Matches the Q-Learning Training Rewards style from the lab reference.

    2. logs/plot_action_heatmap.png
       Normalized action frequency heatmap by game-stage context.
       Context = max tile on the board at the moment of action selection.
       Generated by rolling out 200 greedy games with the trained DQN model.

Usage:
    python rl_analysis.py
    python rl_analysis.py --training-csv logs/dqn_training_<timestamp>.csv
    python rl_analysis.py --model models/dqn_final.pth
    python rl_analysis.py --eval-games 200
"""

import argparse
import os

import matplotlib
matplotlib.use('Agg')   # headless backend — no display required
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import torch

from dqn_agent import DQNAgent
from game import Game2048


# ================================================================
# Context bucketing
# ================================================================

CONTEXT_ORDER  = ['<64', '64', '128', '256', '512', '1024+']
ACTION_LABELS  = ['LEFT', 'RIGHT', 'UP', 'DOWN']


def _context_bucket(board):
    """Return the context label for the current board state.

    Context = max tile value on the board, bucketed into game stages.
    This mirrors the approach used in tabular Q-learning heatmaps but
    derived empirically via policy rollout instead of Q-table counts.
    """
    max_tile = int(np.max(board))
    if max_tile < 64:
        return '<64'
    elif max_tile == 64:
        return '64'
    elif max_tile == 128:
        return '128'
    elif max_tile == 256:
        return '256'
    elif max_tile == 512:
        return '512'
    else:
        return '1024+'


# ================================================================
# Plot 1 — Training Reward Curve
# ================================================================

def plot_reward_curve(training_csv, out_path, rolling_window=1000):
    """Plot episode reward scatter + rolling average from training log CSV."""
    print(f"Loading training log: {training_csv}")
    df = pd.read_csv(training_csv)

    # Drop rows where episode_reward is missing (early episodes before buffer filled)
    df = df.dropna(subset=['episode_reward'])

    episodes = df['episode'].values
    rewards  = df['episode_reward'].values
    rolling  = df['episode_reward'].rolling(rolling_window, min_periods=1).mean().values

    n_episodes = int(episodes[-1])
    gamma      = 0.99   # fixed training parameter

    fig, ax = plt.subplots(figsize=(13, 5))
    fig.patch.set_facecolor('white')
    ax.set_facecolor('#f8f8f8')
    ax.grid(True, color='white', linewidth=0.8, linestyle='--')

    ax.scatter(episodes, rewards, s=4, alpha=0.25, color='steelblue',
               label='Reward per episode', zorder=2)
    ax.plot(episodes, rolling, color='darkorange', linewidth=2.0,
            label=f'Rolling avg (window={rolling_window})', zorder=3)

    ax.axhline(0, color='gray', linewidth=0.8, linestyle='--', zorder=1)

    ax.set_xlabel('Episode', fontsize=13)
    ax.set_ylabel('Total Reward', fontsize=13)
    ax.set_title(
        f'DQN Training Rewards  |  episodes={n_episodes:,} · γ={gamma}',
        fontsize=14, fontweight='bold'
    )
    ax.legend(fontsize=11, framealpha=0.9)

    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {out_path}")


# ================================================================
# Plot 2 — Normalized Action Distribution Heatmap
# ================================================================

def _rollout_action_log(agent, n_games, max_steps=5000):
    """Run n_games greedy games and log (context_bucket, action) per step.

    Returns a 6x4 count matrix indexed by CONTEXT_ORDER x ACTION_LABELS.
    """
    # counts[context][action]
    counts = {ctx: [0, 0, 0, 0] for ctx in CONTEXT_ORDER}
    game   = Game2048()

    for i in range(n_games):
        game.reset()
        steps = 0
        if i % 50 == 0:
            print(f"  Rollout game {i+1}/{n_games}...")

        while not game.game_over and steps < max_steps:
            valid_moves = game.get_valid_moves()
            if not valid_moves:
                break
            ctx    = _context_bucket(game.board)
            action = agent.select_action(game.board, valid_moves)
            counts[ctx][action] += 1
            game.step(action)
            steps += 1

    return counts


def plot_action_heatmap(model_path, n_games, out_path):
    """Load trained DQN and run greedy rollouts to build action heatmap."""
    print(f"Loading model: {model_path}")
    agent = DQNAgent()
    agent.online_net.load_state_dict(torch.load(model_path, weights_only=True))
    agent.target_net.load_state_dict(agent.online_net.state_dict())
    agent.epsilon = 0.0   # greedy

    print(f"Running {n_games} evaluation games for action logging...")
    counts = _rollout_action_log(agent, n_games)

    # Build normalized matrix: rows=context, cols=action
    matrix = np.zeros((len(CONTEXT_ORDER), len(ACTION_LABELS)), dtype=float)
    for ri, ctx in enumerate(CONTEXT_ORDER):
        row_total = sum(counts[ctx])
        if row_total > 0:
            matrix[ri] = [c / row_total for c in counts[ctx]]

    df_heat = pd.DataFrame(matrix, index=CONTEXT_ORDER, columns=ACTION_LABELS)

    fig, ax = plt.subplots(figsize=(9, 5))
    sns.heatmap(
        df_heat,
        ax=ax,
        annot=True,
        fmt='.2f',
        cmap='YlOrRd',
        vmin=0.0,
        vmax=1.0,
        linewidths=0.5,
        linecolor='white',
        cbar_kws={'label': 'Normalized Frequency'},
    )

    ax.set_xlabel('Action', fontsize=12)
    ax.set_ylabel('Context (Max Tile)', fontsize=12)
    ax.set_title(
        f'Normalized Action Distribution by Context\n'
        f'(DQN, 500k episodes, {n_games} eval games)',
        fontsize=13, fontweight='bold'
    )

    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {out_path}")


# ================================================================
# Entry point
# ================================================================

def _latest_training_csv(log_dir='logs'):
    """Return the largest (most complete) training CSV in log_dir."""
    csvs = sorted(
        [f for f in os.listdir(log_dir) if f.startswith('dqn_training_')],
        key=lambda f: os.path.getsize(os.path.join(log_dir, f)),
        reverse=True,
    )
    if not csvs:
        raise FileNotFoundError(f"No dqn_training_*.csv found in {log_dir}/")
    return os.path.join(log_dir, csvs[0])


def main():
    parser = argparse.ArgumentParser(description="Generate DQN analysis plots")
    parser.add_argument('--training-csv', type=str, default=None,
                        help='Training log CSV (default: largest in logs/)')
    parser.add_argument('--model', type=str, default='models/dqn_final.pth',
                        help='Trained model weights (default: models/dqn_final.pth)')
    parser.add_argument('--eval-games', type=int, default=200,
                        help='Greedy games for action heatmap (default: 200)')
    parser.add_argument('--log-dir', type=str, default='logs',
                        help='Directory for CSVs and output PNGs (default: logs/)')
    args = parser.parse_args()

    os.makedirs(args.log_dir, exist_ok=True)

    training_csv = args.training_csv or _latest_training_csv(args.log_dir)

    reward_out  = os.path.join(args.log_dir, 'plot_reward_curve.png')
    heatmap_out = os.path.join(args.log_dir, 'plot_action_heatmap.png')

    print("=== Plot 1: Reward Curve ===")
    plot_reward_curve(training_csv, reward_out)

    print("\n=== Plot 2: Action Heatmap ===")
    plot_action_heatmap(args.model, args.eval_games, heatmap_out)

    print("\nDone.")
    print(f"  {reward_out}")
    print(f"  {heatmap_out}")


if __name__ == '__main__':
    main()
